import {
  DesignProject,
  DesignStudioModuleId,
  DesignProjectSector,
} from '../types';

export const MANDATORY_DESIGN_DISCLAIMER =
  'This document is a preliminary conceptual study generated by LDL Dhenze Builder AI. It is not a signed or sealed architectural or engineering document and cannot be used for construction, regulatory filings, or permit applications without comprehensive review, technical detailing, structural calculations, and authorized dry-sealing by registered and licensed Philippine professionals pursuant to Republic Act No. 9266 and Republic Act No. 544.';

export const MANDATORY_CONCEPTUAL_NOTICE =
  'PRELIMINARY AI-GENERATED CONCEPT - NOT FOR CONSTRUCTION - REQUIRES PRC-LICENSED PROFESSIONAL REVIEW & SEAL';

export const MANDATORY_IMAGE_LABEL =
  'PRELIMINARY AI-GENERATED CONCEPTUAL PERSPECTIVE - NOT FOR CONSTRUCTION';

export interface ModuleDefinition {
  id: DesignStudioModuleId;
  title: string;
  category: string;
  description: string;
  order: number;
  baseCredits: number;
}

export const DESIGN_STUDIO_MODULES: ModuleDefinition[] = [
  { id: 'project-setup', title: 'Project Initialization & Vision', category: 'Foundation', description: 'Configure project typology, jurisdiction, and baseline governance objectives.', order: 1, baseCredits: 20 },
  { id: 'site-info', title: 'Site Topography & Geotechnical Registry', category: 'Foundation', description: 'Log survey coordinates, lot dimensions, boundary setbacks, and geotechnical soil reports.', order: 2, baseCredits: 25 },
  { id: 'requirements-builder', title: 'Functional Brief & Requirements', category: 'Foundation', description: 'Establish user capacity, operational flows, architectural styles, and sustainability targets.', order: 3, baseCredits: 30 },
  { id: 'space-programming', title: 'Spatial Programming & Area Allocations', category: 'Architecture', description: 'Formulate square meter schedules, room adjacencies, and occupancy loads.', order: 4, baseCredits: 40 },
  { id: 'concept-generator', title: 'Architectural Massing & Concept Generator', category: 'Architecture', description: 'Generate AI-driven massing options, volumetric studies, and stylistic orientations.', order: 5, baseCredits: 80 },
  { id: 'site-planning', title: 'Site Layout & Vehicular Access Planning', category: 'Architecture', description: 'Master zoning, road ingress/egress, turning radii, and boundary buffers.', order: 6, baseCredits: 60 },
  { id: 'floor-plan', title: 'Floor Plan Layout Schematic', category: 'Architecture', description: 'Generate preliminary functional 2D floor plans with dimensional gridlines.', order: 7, baseCredits: 75 },
  { id: 'elevation', title: 'Building Elevations & Facade Studies', category: 'Architecture', description: 'Draft exterior elevations detailing fenestration, floor-to-ceiling heights, and materials.', order: 8, baseCredits: 65 },
  { id: 'section', title: 'Longitudinal & Transverse Sections', category: 'Architecture', description: 'Examine structural depth, floor assemblies, ceiling plenums, and roof slopes.', order: 9, baseCredits: 65 },
  { id: 'masterplan', title: 'Estate Master Planning & Phasing', category: 'Urban Design', description: 'Zoning development phases, utility spines, and landscape easements across acreage.', order: 10, baseCredits: 100 },
  { id: 'landscape', title: 'Landscape & Permeability Design', category: 'Architecture', description: 'Native tropical flora selection, bioswales, retention basins, and hardscape paving.', order: 11, baseCredits: 50 },
  { id: 'interior', title: 'Interior Space Concepts & Millwork', category: 'Architecture', description: 'Preliminary interior perspectives, ceiling layout concepts, and bespoke cabinetry.', order: 12, baseCredits: 70 },
  { id: 'exterior-viz', title: 'Photorealistic Exterior Perspectives', category: 'Visualization', description: 'High-resolution exterior 3D perspectives with daylight solar studies.', order: 13, baseCredits: 90 },
  { id: 'structural', title: 'Structural Framing & Lateral Grid Systems', category: 'Engineering', description: 'Preliminary column grid layouts, seismic shear wall locations, and slab sizing.', order: 14, baseCredits: 85 },
  { id: 'electrical', title: 'Electrical Power, Lighting & Single-Line', category: 'Engineering', description: 'Transformer sizing, load schedules, generator backup, and circuit risers.', order: 15, baseCredits: 75 },
  { id: 'mechanical', title: 'HVAC, Ventilation & Air Exchange', category: 'Engineering', description: 'Chiller/VRF sizing, duct routings, fresh air intake, and pressurization.', order: 16, baseCredits: 75 },
  { id: 'plumbing-sanitary', title: 'Plumbing, Drainage & Water Supply', category: 'Engineering', description: 'Potable water storage, sanitary sewer risers, and stormwater collection.', order: 17, baseCredits: 65 },
  { id: 'fire-safety', title: 'Fire Protection & Life Safety Compliance', category: 'Engineering', description: 'Sprinkler coverage, dry standpipes, egress travel distances, and fire pump rooms.', order: 18, baseCredits: 60 },
  { id: 'renewable-energy', title: 'Solar PV & Battery Energy Storage (BESS)', category: 'Sustainability', description: 'Rooftop/ground solar capacity modeling, inverter sizing, and peak shaving.', order: 19, baseCredits: 70 },
  { id: 'water-environmental', title: 'Rainwater Harvesting & Wastewater (STP)', category: 'Sustainability', description: 'Decentralized sewage treatment, effluent recycling, and graywater irrigation.', order: 20, baseCredits: 60 },
  { id: 'agro-industrial', title: 'Cold Storage & Agro-Processing Systems', category: 'Industrial', description: 'Cold storage thermal envelopes, dock seals, processing lines, and pallet storage.', order: 21, baseCredits: 85 },
  { id: 'smart-building', title: 'Smart BMS, Automation & Telemetry', category: 'Technology', description: 'IoT sensor meshes, central automated building management, and access controls.', order: 22, baseCredits: 65 },
  { id: 'smart-city', title: 'Micro-Grid & Community Telemetry', category: 'Technology', description: 'District smart meters, solar micro-grid distribution, and fiber backbone planning.', order: 23, baseCredits: 95 },
  { id: 'materials-finishes', title: 'Materials Schedule & Finish Palette', category: 'Specifications', description: 'Specifying commercial-grade concrete, structural steel, low-E glazing, and cladding.', order: 24, baseCredits: 40 },
  { id: 'preliminary-quantities', title: 'Takeoff & Quantity Estimating (BOQ)', category: 'Estimating', description: 'Automated volume calculations for earthworks, concrete, rebar, and finishes.', order: 25, baseCredits: 80 },
  { id: 'budget-framework', title: 'Capital Expenditure & Budget Framework', category: 'Estimating', description: 'Cost per square meter modeling benchmarked against Philippine civil indices.', order: 26, baseCredits: 60 },
  { id: 'equipment-planning', title: 'Heavy Equipment & Logistics Logistics', category: 'Operations', description: 'Tower crane radiuses, excavator sizing, batching plant access, and haul routes.', order: 27, baseCredits: 50 },
  { id: 'construction-schedule', title: 'Baseline Milestone Schedule (WBS)', category: 'Operations', description: 'Gantt-based work breakdown structure, procurement lead times, and critical paths.', order: 28, baseCredits: 70 },
  { id: 'risk-compliance', title: 'Regulatory Compliance & Risk Matrix', category: 'Governance', description: 'Philippine National Building Code (PD 1096), Fire Code (RA 9514), and DOLE DO 13.', order: 29, baseCredits: 55 },
  { id: 'drawing-set-builder', title: 'Multi-Sheet Drawing Set Compiler', category: 'Documentation', description: 'Compile architectural and engineering sheets into indexed title-blocked sets.', order: 30, baseCredits: 75 },
  { id: 'professional-review', title: 'PRC Licensed Professional Review Hub', category: 'Governance', description: 'Submit preliminary packages for PRC architect/engineer stamping and statutory review.', order: 31, baseCredits: 50 },
  { id: 'version-comparison', title: 'Revision Diff & Version Tracking', category: 'Documentation', description: 'Compare revisions side-by-side highlighting footprint, cost, and structural adjustments.', order: 32, baseCredits: 35 },
  { id: 'client-presentation', title: 'Interactive Client Brief & Pitch Deck', category: 'Presentation', description: 'Synthesize executive summary, renders, cost ranges, and milestones for owners.', order: 33, baseCredits: 45 },
  { id: 'export-center', title: 'Executive Document & CAD/BIM Exporter', category: 'Export', description: 'Export verified packages to PDF, IFC, DWG, and detailed Excel BOQ schedules.', order: 34, baseCredits: 40 },
  { id: 'credit-usage-center', title: 'Studio Ledger & Consumption Audit', category: 'Accounting', description: 'Audit token consumption, generation charges, and team wallet allocations.', order: 35, baseCredits: 10 },
];

export interface SectorDefinition {
  sector: DesignProjectSector;
  types: string[];
  description: string;
}

export const SECTORS_AND_TYPES: SectorDefinition[] = [
  {
    sector: 'Residential',
    types: ['Single-Family Luxury Estate', 'Contemporary Multi-Story Villa', 'Boutique Townhouse Cluster', 'Mid-Rise Residential Condominium'],
    description: 'Bespoke modern residential architecture engineered for seismic resilience, thermal comfort, and tropical elegance.',
  },
  {
    sector: 'Commercial',
    types: ['Mixed-Use Commercial Center', 'Corporate Office Building', 'Retail Strip Center', 'Hospitality & Boutique Resort'],
    description: 'High-efficiency commercial developments designed to maximize tenant yield, pedestrian circulation, and operational longevity.',
  },
  {
    sector: 'Industrial and Logistics',
    types: ['High-Bay Logistics Warehouse', 'Cold Chain Distribution Center', 'Manufacturing Assembly Facility', 'Container Yard & Intermodal Depot'],
    description: 'Heavy-duty industrial infrastructure featuring wide-span steel frames, heavy slab loading, and logistics efficiency.',
  },
  {
    sector: 'Institutional',
    types: ['Healthcare & Medical Clinic Facility', 'Educational Campus & Training Center', 'Civic Administration Complex', 'Community Sports Pavilion'],
    description: 'Institutional facilities meeting strict national standards for life safety, accessibility (BP 344), and community service.',
  },
  {
    sector: 'Agriculture and Agro-Industrial',
    types: ['Controlled-Atmosphere Cold Storage', 'Automated Livestock Housing', 'Post-Harvest Grains Processing Plant', 'Hydroponic & Greenhousing Complex'],
    description: 'Specialized agricultural facilities protecting food security with integrated cold chains and hygienic processing envelopes.',
  },
  {
    sector: 'Energy and Environment',
    types: ['Utility-Scale Solar Farm', 'Distributed Rooftop PV Array', 'Battery Energy Storage System (BESS)', 'Decentralized Sewage Treatment Plant (STP)'],
    description: 'Clean energy generation and environmental utilities powering off-grid developments and commercial facilities.',
  },
  {
    sector: 'Infrastructure and Smart Development',
    types: ['Subdivision Road & Drainage Network', 'Water Reservoir & Pumping Station', 'Smart City Telemetry Backbone', 'Flood Retention & Slope Protection'],
    description: 'Robust civil infrastructure and municipal-grade utilities engineered to withstand extreme typhoon and seismic conditions.',
  },
];

export const INITIAL_DESIGN_PROJECTS: DesignProject[] = [
  {
    id: 'prj-ds-001',
    title: 'The Clark Highlands Luxury Estate Villa',
    organizationId: 'org-dhenze-internal',
    clientName: 'Don Eduardo Miranda',
    clientEmail: 'e.miranda@clarkholdings.ph',
    sector: 'Residential',
    projectType: 'Single-Family Luxury Estate',
    description: 'Two-story contemporary tropical estate with private infinity pool, solar microgrid, and integrated storm drainage in Angeles City, Pampanga.',
    location: 'Clark Highlands, Angeles City, Pampanga',
    stage: 'Concept',
    status: 'In Design',
    floorAreaSqM: 680,
    lotAreaSqM: 1200,
    floorsCount: 2,
    estimatedBudgetPHP: '₱42,500,000',
    targetCommencement: '2026-11-01',
    targetCompletion: '2027-10-31',
    createdAt: '2026-08-15T08:00:00Z',
    updatedAt: '2026-09-12T14:30:00Z',
    currentVersion: 'v1.2',
    versionsCount: 2,
    drawingSheetsCount: 3,
    creditsSpent: 180,
    siteInfo: {
      dimensions: '30.0m frontage x 40.0m depth',
      boundaryNotes: 'Bounded by residential lot on North and East, private subdivision road on West.',
      roadAccess: '12-meter wide paved subdivision arterial road.',
      orientation: 'Frontage facing West, primary living areas oriented North-South for passive cooling.',
      topography: 'Gently sloping 2% toward roadway drainage easement.',
      floodRisk: 'Zero historical flood record; elevated site.',
      zoning: 'R-1 Low-Density Luxury Residential.',
      setbacks: 'Front 5.0m, Sides 3.0m, Rear 4.0m.',
      easements: '2.0m drainage right-of-way along rear boundary.',
      heightRestrictions: 'Maximum 10.0m allowable building height.',
    },
    requirements: {
      architecturalStyle: 'Contemporary Tropical Minimalist',
      primaryMaterials: ['Fair-faced reinforced concrete', 'Hardwood louvers', 'Low-E solar glazing', 'Travertine paving'],
      sustainabilityGoals: ['15kW rooftop solar PV', 'Rainwater harvesting cistern', 'Passive cross-ventilation', 'LED smart dimming'],
      parkingSlots: 4,
      accessibilityCompliance: true,
      solarReadiness: true,
      rainwaterHarvesting: true,
      bmsAutomation: true,
    },
    spaceProgram: [
      {
        id: 'sp-01',
        name: 'Great Hall & Living Pavilion',
        zone: 'Public',
        quantity: 1,
        minAreaSqM: 70,
        targetAreaSqM: 85,
        maxAreaSqM: 100,
        capacityPersons: 20,
        occupancyType: 'Assembly / Living',
        adjacencies: ['Dining Terrace', 'Foyer', 'Pool Lanai'],
        privacyLevel: 'Low',
        naturalLight: 'High',
        ventilation: 'Natural',
        equipment: ['Central AV Console', 'Integrated Climate Sensors'],
      },
      {
        id: 'sp-02',
        name: 'Master Suite Retreat',
        zone: 'Private',
        quantity: 1,
        minAreaSqM: 60,
        targetAreaSqM: 75,
        maxAreaSqM: 90,
        capacityPersons: 2,
        occupancyType: 'Sleeping',
        adjacencies: ['Master Walk-in Wardrobe', 'Ensuite Bath', 'Private Balcony'],
        privacyLevel: 'High',
        naturalLight: 'High',
        ventilation: 'Hybrid',
        equipment: ['Smart Temperature Control', 'Motorized Louvers'],
      },
    ],
    drawingSheets: [
      {
        id: 'ds-sheet-001',
        sheetNumber: 'A-101',
        title: 'Ground Floor Architectural Plan',
        scale: '1:100',
        category: 'Architectural',
        status: 'Preliminary Concept',
        date: '2026-09-12T14:30:00Z',
        version: '1.0',
        generatedBy: 'LDL Dhenze Builder AI Design Engine',
        reviewStatus: 'Pending Professional Review',
        qrCode: 'VERIFY-LDL-DS001-A101',
        disclaimer: MANDATORY_DESIGN_DISCLAIMER,
        notes: 'Preliminary layout. Requires structural coordinate verification.',
      },
    ],
    options: [
      {
        id: 'opt-01',
        optionKey: 'Option A',
        title: 'Option A: Courtyard Layout with Integrated Lap Pool',
        description: 'U-shaped floor plan maximizing internal privacy with central water courtyard.',
        floorAreaSqM: 680,
        siteUtilizationPercent: 42,
        capacityOccupants: 12,
        circulationScore: 92,
        naturalLightScore: 95,
        costRangePHP: '₱42,500,000 - ₱45,000,000',
        scheduleMonths: 12,
        advantages: ['Enhanced privacy from neighbors', 'Optimal natural cross-ventilation'],
        limitations: ['Slightly higher exterior wall surface area'],
        sustainabilityRating: 'High Solar Readiness (BERDE 4-Star)',
      },
    ],
    versions: [
      {
        id: 'ver-01',
        versionNumber: 'v1.0',
        revisionNumber: 1,
        description: 'Initial conceptual massing and spatial brief.',
        timestamp: '2026-08-15T08:00:00Z',
        requestedBy: 'Don Eduardo Miranda',
        generatedBy: 'LDL Dhenze Builder AI',
        creditCost: 80,
        reviewStatus: 'Preliminary Concept',
        assumptions: ['Assumed 150 kPa allowable soil bearing capacity', 'Assumed municipal water connection'],
        limitations: ['Not for construction; requires PRC structural stamping'],
        changesSummary: 'Initial setup of project geometry and room schedule.',
      },
    ],
    reviews: [],
  },
];
